In [3]:
import numpy as np

matrix = np.array([
    [12, 45, 78, 80],
    [56, 78, 90, 123],
    [34, 56, 78, 80],
    [45, 67, 89, 100],
    [23, 45, 67, 78],
    [78, 90, 123, 145],
    [56, 78, 90, 123],
    [34, 56, 78, 80]
])

matrix_min = np.min(matrix)
matrix_max = np.max(matrix)

normalized_matrix = (matrix - matrix_min) / (matrix_max - matrix_min) * 255

print("Matrice normalisée (intervalle [0, 255]) :")
print(normalized_matrix)


Matrice normalisée (intervalle [0, 255]) :
[[  0.          63.27067669 126.54135338 130.37593985]
 [ 84.36090226 126.54135338 149.54887218 212.81954887]
 [ 42.18045113  84.36090226 126.54135338 130.37593985]
 [ 63.27067669 105.45112782 147.63157895 168.72180451]
 [ 21.09022556  63.27067669 105.45112782 126.54135338]
 [126.54135338 149.54887218 212.81954887 255.        ]
 [ 84.36090226 126.54135338 149.54887218 212.81954887]
 [ 42.18045113  84.36090226 126.54135338 130.37593985]]
